require File.expand_path('../../config/environment.rb', __FILE__)

Comedian.create(name: "Katt Williams", age: "47", city: "Cincinati")
Comedian.create(name: "Martin Lawrence", age: "53", city: "Frankfurt")
Comedian.create(name: "Christopher Tucker", age: "47", city: "Atlanta")
Comedian.create(name: "Bernie Mac", age: "61", city: "Chicago")
Comedian.create(name: "Eddie Murphy", age: "57", city: "Brooklyn")
Comedian.create(name: "Dave Chapelle", age: "45", city: "Washington D.C.")
Comedian.create(name: "Paul Mooney", age: "77", city: "Shreveport")
Comedian.create(name: "Cedric the Entertainer", age: "54", city: "Jefferson City")
Comedian.create(name: "Chris Rock", age: "53", city: "Anderson")
Comedian.create(name: "Jim Gaffigan", age: "52", city: "Elgin")
Comedian.create(name: "Richard Pryor", age: "78", city: "Peoria")
Comedian.create(name: "Bill Burr", age: "50", city: "Canton")

Special.create(comedian_id: 1, name:"The Pimp Chronicles Pt. 1",run_length: 45, image_url: "https://m.media-amazon.com/images/M/MV5BODUwOTgyMjUtMTVkZS00N2IzLWE5ZDQtZjY1MWIxYjVhODE5XkEyXkFqcGdeQXVyNDUxMTg2MTU@._V1_SY1000_CR0,0,666,1000_AL_.jpg")
Special.create(comedian_id: 2, name:"Doin Time: Uncut",run_length: 62, image_url: "https://m.media-amazon.com/images/M/MV5BMzQyMjI2MTItYzdjNi00MWUzLWFkNjItZWI3ZjEwMzdiNDhmXkEyXkFqcGdeQXVyNDUxMTg2MTU@._V1_SY1000_CR0,0,666,1000_AL_.jpg")
Special.create(comedian_id: 3, name:"Chris Tucker Live",run_length: 92, image_url: "https://m.media-amazon.com/images/M/MV5BMTU1MzU2Njg2MF5BMl5BanBnXkFtZTgwNTM0MzgxNjE@._V1_SY1000_CR0,0,674,1000_AL_.jpg")
Special.create(comedian_id: 4, name:"Midnight Mac",run_length: 90, image_url: "https://m.media-amazon.com/images/M/MV5BMzcwNmMwODQtNGY0Mi00NzRmLWIxMDItZTY4Y2VmZjEyNmRlXkEyXkFqcGdeQXVyODQ1NTk5OQ@@._V1_.jpg")
Special.create(comedian_id: 5, name:"Delirious",run_length: 69, image_url: "https://m.media-amazon.com/images/M/MV5BMTQ5MDcyODU0Nl5BMl5BanBnXkFtZTcwMTgxNjA0MQ@@._V1_.jpg")
Special.create(comedian_id: 6, name:"Killin Them Softly",run_length: 57, image_url: "https://m.media-amazon.com/images/M/MV5BMTcyOGMxN2MtYzUwYy00YzQxLTgwZTItZjAxZTIzYWM1YzEyXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_.jpg")
Special.create(comedian_id: 7, name:"A piece of my mind",run_length: 86, image_url: "https://m.media-amazon.com/images/M/MV5BMGNjYjkwNTQtZjg4MS00MjgzLWJmMjAtZGI3ZGI3NGZmN2FhXkEyXkFqcGdeQXVyNTM3MDMyMDQ@._V1_.jpg")
Special.create(comedian_id: 8, name:"Cedric The Entertainer: Live from the Ville",run_length: 86, image_url: "https://m.media-amazon.com/images/M/MV5BMTQ5NzgxNDcxOV5BMl5BanBnXkFtZTgwMTg1NjEwMDI@._V1_SY1000_CR0,0,674,1000_AL_.jpg")
Special.create(comedian_id: 9, name:"A piece of my mind",run_length: 86, image_url: "https://m.media-amazon.com/images/M/MV5BMGNjYjkwNTQtZjg4MS00MjgzLWJmMjAtZGI3ZGI3NGZmN2FhXkEyXkFqcGdeQXVyNTM3MDMyMDQ@._V1_.jpg")
Special.create(comedian_id: 10, name:"Noble Ape",run_length: 70, image_url: "https://m.media-amazon.com/images/M/MV5BODAyZjM3OGMtZmY2Zi00YjM0LTlhZDYtNTZmYmM2ODQ4NTNiXkEyXkFqcGdeQXVyMzcwMjcwNQ@@._V1_SY1000_CR0,0,666,1000_AL_.jpg")
Special.create(comedian_id: 11, name:"Richard Pryor: Live in Concert",run_length: 78, image_url: "https://m.media-amazon.com/images/M/MV5BMTg4NDkwMzYwNF5BMl5BanBnXkFtZTYwNTMzMTQ5._V1_.jpg")
Special.create(comedian_id: 12, name:"Walk Your Way Out",run_length: 77, image_url: "https://m.media-amazon.com/images/M/MV5BMGYwNDE4MDItNjQwYi00NWIwLWJmYTYtY2I5NDEyMGUxNWMwL2ltYWdlXkEyXkFqcGdeQXVyMjUwMTM3MTU@._V1_.jpg")
